### ISSUE TITLE
Add Column Grow option

### ISSUE THREAD

**Issue by erwstout** [erwstout/ginger#20]
By default columns have a flex property of `flex: 0 1 $flex-basis;`

In some cases when the columns wrap it may be nice for those to grow. Adding a `.col-grow`  or something similar could possibly be a nice feature. Would possibly have to be added to as a `row` option.

In current project my override looks like this:

``` scss
.row{
    max-width: 100%;
    flex-wrap: wrap;
    .col-4{
      background: white;
      flex: 1 1 33.333%;
      padding: 15px 6px;
      &:nth-child(1), &:nth-child(4){
        padding-left: 12px;
      }
      &:nth-child(3), &:nth-child(5){
        padding-right: 12px;
      }
      &:nth-child(4), &:nth-child(5){
        padding-top: 0;
      }
    }
```

![screen shot 2016-04-12 at 4 33 39 pm](https://cloud.githubusercontent.com/assets/9441913/14478637/57f83d36-00cc-11e6-90b9-24fd0685234a.png)
