### ISSUE TITLE
Visibility Classes should have display property options

### ISSUE THREAD

**Issue by erwstout** [erwstout/ginger#31]
In some cases using `desktop-only` (which adds `display: block`) can break layouts that may be flex items. It would be nice to have a class such as `desktop-only--flex` to display the element as a flex element instead.

``` scss
.desktop-only{
  display: block !important;
  &--flex{
    display: flex !important;
  }
}
```
