### ISSUE TITLE
Small Columns Need different flex value

### ISSUE THREAD

**Issue by erwstout** [erwstout/ginger#45]
When using `sm-col-` the `flex-basis` value is added correctly, but since default columns have `flex: 1 1 auto` it doesn't apply correctly. 
![screen shot 2016-12-08 at 4 29 24 pm](https://cloud.githubusercontent.com/assets/9441913/21031946/89ed15b0-bd63-11e6-885a-550f1809193d.png)

**Comment by erwstout** [comment]
This snippet wrapped in a small breakpoint media query fixes the issue:

```scss
  // Ginger Bug Fix
  *[class*="sm-col-"]{
    flex-grow: 0;
  }
```
